services:
    laravel.test:
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1234
        image: sail-8.2/app
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        networks:
            - sail
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - .:/var/www/html
        depends_on:
            - oracle-db

    oracle-db:
        container_name: oracle-db
        image: container-registry.oracle.com/database/free:latest
        ports:
            - "${DB_PORT:-1521}:1521"
            - "5500:5500"
        networks:
            - sail
        environment:
            - ORACLE_PWD=${DB_PASSWORD}
        volumes:
            - ./oracle_database:/opt/oracle/oradata
            - ./docker/oracle:/docker-entrypoint-initdb.d/setup

networks:
    sail:
        driver: bridge
