GRANT CONNECT TO C##kozossegi_oldal CONTAINER=CURRENT;
GRANT CREATE SESSION TO C##kozossegi_oldal CONTAINER=CURRENT;
GRANT RESOURCE TO C##kozossegi_oldal CONTAINER=CURRENT;

ALTER USER C##kozossegi_oldal QUOTA UNLIMITED ON USERS;
