ALTER SESSION SET CURRENT_SCHEMA = C##kozossegi_oldal;

-- Néhány kifejezés miatt kell
SET sqlblanklines ON;

-- FELHASZNALO - V64FGJ
CREATE TABLE "FELHASZNALO"
(
    AZONOSITO       NUMBER(10, 0) GENERATED ALWAYS as IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    VEZETEKNEV      VARCHAR2(100) NOT NULL,
    KERESZTNEV      VARCHAR2(100) NOT NULL,
    EMAIL           VARCHAR2(100) NOT NULL UNIQUE,
    JELSZO          VARCHAR2(100) NOT NULL,
    SZEREP          NUMBER(1, 0)  NOT NULL,
    SZULETESI_DATUM DATE          NOT NULL,
    MUNKAHELY       VARCHAR2(100) DEFAULT NULL,
    ISKOLA          VARCHAR2(100) DEFAULT NULL,
    BECENEV         VARCHAR2(100) DEFAULT NULL,
    PROFILKEP       VARCHAR2(12)  DEFAULT NULL,
    LAKHELY         VARCHAR2(100) DEFAULT NULL,
    SZULOVAROS      VARCHAR2(100) DEFAULT NULL,
    TELEFONSZAM     VARCHAR2(100) DEFAULT NULL
);

-- ISMEROS - V64FGJ

CREATE TABLE "ISMEROS"
(
    KERELMEZO_AZONOSITO NUMBER(10, 0),
    FOGADO_AZONOSITO    NUMBER(10, 0),

    CONSTRAINT pk_ismeros PRIMARY KEY (KERELMEZO_AZONOSITO, FOGADO_AZONOSITO),

    CONSTRAINT fk_ISMEROS_kerelmezo FOREIGN KEY (KERELMEZO_AZONOSITO)
        REFERENCES "FELHASZNALO" (AZONOSITO)
            ON DELETE CASCADE,

    CONSTRAINT fk_ISMEROS_fogado FOREIGN KEY (FOGADO_AZONOSITO)
        REFERENCES "FELHASZNALO" (AZONOSITO)
            ON DELETE CASCADE
);

-- PRIVAT_UZENET - V64FGJ


CREATE TABLE "PRIVAT_UZENET"
(
    AZONOSITO        NUMBER(10, 0) GENERATED ALWAYS as IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    SZOVEG           CLOB,
    KULDO_AZONOSITO  NUMBER(10, 0),
    FOGADO_AZONOSITO NUMBER(10, 0),
    ELKULDESI_IDO    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_PRIVAT_UZENET_kuldo FOREIGN KEY (KULDO_AZONOSITO)
        REFERENCES "FELHASZNALO" (AZONOSITO)
            ON DELETE CASCADE,

    CONSTRAINT fk_PRIVAT_UZENET_fogado FOREIGN KEY (FOGADO_AZONOSITO)
        REFERENCES "FELHASZNALO" (AZONOSITO)
            ON DELETE CASCADE
);

-- CSOPORT - V64FGJ

CREATE TABLE "CSOPORT"
(
    AZONOSITO   NUMBER(7, 0) GENERATED ALWAYS as IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    CSOPORT_NEV VARCHAR2(100),
    TULAJ       NUMBER(10, 0),

    CONSTRAINT fk_CSOPORT_tulaj FOREIGN KEY (TULAJ)
        REFERENCES "FELHASZNALO" (AZONOSITO)
            ON DELETE CASCADE
);

-- TAG - V64FGJ

CREATE TABLE "TAG"
(
    KERELMEZO_AZONOSITO NUMBER(10, 0),
    FOGADO_AZONOSITO    NUMBER(10, 0),
    CSOPORT_AZONOSITO   NUMBER(7, 0),

    CONSTRAINT pk_tag PRIMARY KEY (KERELMEZO_AZONOSITO, FOGADO_AZONOSITO, CSOPORT_AZONOSITO),

    CONSTRAINT fk_TAG_kerelmezo FOREIGN KEY (KERELMEZO_AZONOSITO)
        REFERENCES "FELHASZNALO" (AZONOSITO)
            ON DELETE CASCADE,

    CONSTRAINT fk_TAG_fogado FOREIGN KEY (FOGADO_AZONOSITO)
        REFERENCES "FELHASZNALO" (AZONOSITO)
            ON DELETE CASCADE,

    CONSTRAINT fk_TAG_csoport FOREIGN KEY (CSOPORT_AZONOSITO)
        REFERENCES "CSOPORT" (AZONOSITO)
            ON DELETE CASCADE
);

-- CSOPORT_UZENET - V64FGJ

CREATE TABLE "CSOPORT_UZENET"
(
    AZONOSITO         NUMBER(10, 0) GENERATED ALWAYS as IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    SZOVEG            CLOB,
    KULDO_AZONOSITO   NUMBER(10, 0),
    CSOPORT_AZONOSITO NUMBER(7, 0),
    ELKULDESI_IDO     TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_CSOPORT_UZENET_kuldo FOREIGN KEY (KULDO_AZONOSITO)
        REFERENCES "FELHASZNALO" (AZONOSITO)
            ON DELETE CASCADE,

    CONSTRAINT fk_CSOPORT_UZENET_csoport FOREIGN KEY (CSOPORT_AZONOSITO)
        REFERENCES "CSOPORT" (AZONOSITO)
            ON DELETE CASCADE
);

-- SZOVEGES_BEJEGYZES - E22EDJ

CREATE TABLE "SZOVEGES_BEJEGYZES"
(
    AZONOSITO             NUMBER(10) GENERATED ALWAYS as IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    SZOVEG                CLOB       NOT NULL,
    KOZZETETELI_IDO       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FELHASZNALO_AZONOSITO NUMBER(10) NOT NULL,

    CONSTRAINT fk_SZOVEGES_BEJEGYZES_felhasznalo_azonosito FOREIGN KEY (FELHASZNALO_AZONOSITO)
        REFERENCES FELHASZNALO (AZONOSITO)
            ON DELETE CASCADE
);

CREATE TABlE "SZOVEGES_BEJEGYZES_KOMMENT"
(
    AZONOSITO                    NUMBER(10) GENERATED ALWAYS as IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    SZOVEG                       CLOB       NOT NULL,
    ELKULDESI_IDO                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FELHASZNALO_AZONOSITO        NUMBER(10) NOT NULL,
    SZOVEGES_BEJEGYZES_AZONOSITO NUMBER(10) NOT NULL,

    CONSTRAINT fk_SZOVEGES_BEJEGYZES_KOMMENT_felhasznalo_azonosito FOREIGN KEY (FELHASZNALO_AZONOSITO)
        REFERENCES FELHASZNALO (AZONOSITO)
            ON DELETE CASCADE,

    CONSTRAINT fk_SZOVEGES_BEJEGYZES_KOMMENT_szoveges_bejegyzes_komment FOREIGN KEY (SZOVEGES_BEJEGYZES_AZONOSITO)
        REFERENCES SZOVEGES_BEJEGYZES (AZONOSITO)
            ON DELETE CASCADE
);

CREATE TABlE "SZOVEGES_BEJEGYZES_REAKCIO"
(
    FELHASZNALO_AZONOSITO        NUMBER(10) NOT NULL,
    SZOVEGES_BEJEGYZES_AZONOSITO NUMBER(10) NOT NULL,
    REAKCIO                      NUMBER(1)  NOT NULL
        CONSTRAINT SZOVEGES_BEJEGYZES_REAKCIO_check_reakcio CHECK (REAKCIO IN (0, 1)),

    PRIMARY KEY (FELHASZNALO_AZONOSITO, SZOVEGES_BEJEGYZES_AZONOSITO),

    CONSTRAINT fk_SZOVEGES_BEJEGYZES_REAKCIO_felhasznalo_azonosito FOREIGN KEY (FELHASZNALO_AZONOSITO)
        REFERENCES FELHASZNALO (AZONOSITO)
            ON DELETE CASCADE,

    CONSTRAINT fk_SZOVEGES_BEJEGYZES_REAKCIO_szoveges_bejegyzes_azonosito FOREIGN KEY (SZOVEGES_BEJEGYZES_AZONOSITO)
        REFERENCES SZOVEGES_BEJEGYZES (AZONOSITO)
            ON DELETE CASCADE
);

-- KEPES_BEJEGYZES - E22EDJ

CREATE TABLE "KEPES_BEJEGYZES"
(
    AZONOSITO             NUMBER(10) GENERATED ALWAYS as IDENTITY (START WITH 1 INCREMENT BY 1),
    KEP                   VARCHAR(12) NOT NULL,
    KOZZETETELI_IDO       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FELHASZNALO_AZONOSITO NUMBER(10)  NOT NULL,

    CONSTRAINT PK_KEPES_BEJEGYZES PRIMARY KEY (AZONOSITO),

    CONSTRAINT fK_KEPES_BEJEGYZES_felhasznalo_azonosito FOREIGN KEY (FELHASZNALO_AZONOSITO)
        REFERENCES FELHASZNALO (AZONOSITO)
            ON DELETE CASCADE
);

-- KEPES_BEJEGYZES_KOMMENT - E22EDJ

CREATE TABlE "KEPES_BEJEGYZES_KOMMENT"
(
    AZONOSITO                 NUMBER(10) GENERATED ALWAYS as IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    SZOVEG                    CLOB       NOT NULL,
    ELKULDESI_IDO             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FELHASZNALO_AZONOSITO     NUMBER(10) NOT NULL,
    KEPES_BEJEGYZES_AZONOSITO NUMBER(10) NOT NULL,

    CONSTRAINT fk_KEPES_BEJEGYZES_KOMMENT_felhasznalo_azonosito FOREIGN KEY (FELHASZNALO_AZONOSITO)
        REFERENCES FELHASZNALO (AZONOSITO)
            ON DELETE CASCADE,

    CONSTRAINT fk_KEPES_BEJEGYZES_KOMMENT_szoveges_bejegyzes_azonosito FOREIGN KEY (KEPES_BEJEGYZES_AZONOSITO)
        REFERENCES KEPES_BEJEGYZES (AZONOSITO)
            ON DELETE CASCADE
);

-- KEPES_BEJEGYZES_REAKCIO - E22EDJ

CREATE TABlE "KEPES_BEJEGYZES_REAKCIO"
(
    FELHASZNALO_AZONOSITO     NUMBER(10) NOT NULL,
    KEPES_BEJEGYZES_AZONOSITO NUMBER(10) NOT NULL,
    REAKCIO                   NUMBER(1)  NOT NULL
        CONSTRAINT KEPES_BEJEGYZES_REAKCIO_check_reakcio CHECK (REAKCIO IN (0, 1)),

    CONSTRAINT pk_KEPES_BEJEGYZES_REAKCIO PRIMARY KEY (FELHASZNALO_AZONOSITO, KEPES_BEJEGYZES_AZONOSITO),

    CONSTRAINT fk_KEPES_BEJEGYZES_REAKCIO_felhasznalo_azonosito FOREIGN KEY (FELHASZNALO_AZONOSITO)
        REFERENCES FELHASZNALO (AZONOSITO)
            ON DELETE CASCADE,

    CONSTRAINT fk_KEPES_BEJEGYZES_REAKCIO_kepes_bejegyzes_azonosito FOREIGN KEY (KEPES_BEJEGYZES_AZONOSITO)
        REFERENCES KEPES_BEJEGYZES (AZONOSITO)
            ON DELETE CASCADE
);

CREATE TABLE KEPES_BEJEGYZES_REAKCIO_AGGREGATE
(
    AZONOSITO NUMBER(10) GENERATED ALWAYS as IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    BEJEGYZES_AZONOSITO NUMBER(10),
    AGGREGALT_LIKE_MENNYISEG INT DEFAULT 0,
    AGGREGALT_DISLIKE_MENNYISEG INT DEFAULT 0,

    CONSTRAINT fk_KEPES_BEJEGYZES_REAKCIO_AGGREGATE_BEJEGYZES_AZONOSITO FOREIGN KEY (BEJEGYZES_AZONOSITO)
        REFERENCES KEPES_BEJEGYZES(AZONOSITO)
            ON DELETE CASCADE
);

CREATE TABLE SZOVEGES_BEJEGYZES_REAKCIO_AGGREGATE
(
    AZONOSITO NUMBER(10) GENERATED ALWAYS as IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    BEJEGYZES_AZONOSITO NUMBER(10),
    AGGREGALT_LIKE_MENNYISEG INT DEFAULT 0,
    AGGREGALT_DISLIKE_MENNYISEG INT DEFAULT 0,

    CONSTRAINT fk_SZOVEGES_BEJEGYZES_REAKCIO_AGGREGATE_BEJEGYZES_AZONOSITO FOREIGN KEY (BEJEGYZES_AZONOSITO)
        REFERENCES SZOVEGES_BEJEGYZES(AZONOSITO)
            ON DELETE CASCADE
);
