-- ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = C##kozossegi_oldal;

-- ADATOK LÉTREHOZÁSA - WQBT9A

Insert into FELHASZNALO (VEZETEKNEV,KERESZTNEV,EMAIL,JELSZO,SZEREP,SZULETESI_DATUM) values ('Fekete','Viktor','Fv11@gmail.com','b5c9ad0015e600d9807f897099927989403263302f42b3cfac1e41f7e380bad8','1',to_date('1999/05/06','yyyy/mm/dd'));
Insert into FELHASZNALO (VEZETEKNEV,KERESZTNEV,EMAIL,JELSZO,SZEREP,SZULETESI_DATUM) values ('Fekete','Emil','Fv12@gmail.com','7133314a68b0f8b4f7e2866ac2e1bba883c8dd8743dc0defc5bf0a4ec48c048d','0',to_date('1989/01/01','yyyy/mm/dd'));
Insert into FELHASZNALO (VEZETEKNEV,KERESZTNEV,EMAIL,JELSZO,SZEREP,SZULETESI_DATUM) values ('Barna','Lajos','Bl1@gmail.com','81f57514f5cbcbfa509886b339e611bfcf2f4288469ba051692dc2eb5a870566','1',to_date('1970/09/11','yyyy/mm/dd'));
Insert into FELHASZNALO (VEZETEKNEV,KERESZTNEV,EMAIL,JELSZO,SZEREP,SZULETESI_DATUM) values ('Barna','Ferenc','Bf2@gmail.com','ad753b822a0582590680429a0e1d96123a9a0084808103b44f65284aaf3c8e81','0',to_date('1983/01/12','yyyy/mm/dd'));
Insert into FELHASZNALO (VEZETEKNEV,KERESZTNEV,EMAIL,JELSZO,SZEREP,SZULETESI_DATUM) values ('Barna','Viktor','Bv3@gmail.com','fcf924d949b2ce4778d22d6b17a8f4826155cd3226040b6de252b046f9b0add4','0',to_date('1997/02/08','yyyy/mm/dd'));
Insert into FELHASZNALO (VEZETEKNEV,KERESZTNEV,EMAIL,JELSZO,SZEREP,SZULETESI_DATUM) values ('Balogh','Janos','Bj4@gmail.com','b1b950ca1591ca15043d363b0c045eec016a5e236ba008c3a4dc60d0a9d21446','0',to_date('1992/06/04','yyyy/mm/dd'));
Insert into FELHASZNALO (VEZETEKNEV,KERESZTNEV,EMAIL,JELSZO,SZEREP,SZULETESI_DATUM) values ('Balogh','Irma','Bi5@gmail.com','43d64cbf2755494a2a15b178a6f9855c6404bbbdc974c94cebc2862195f6ebdc','0',to_date('1989/01/01','yyyy/mm/dd'));
Insert into FELHASZNALO (VEZETEKNEV,KERESZTNEV,EMAIL,JELSZO,SZEREP,SZULETESI_DATUM) values ('Balogh','Vilmos','Bv6@gmail.com','9f107926e19b1998c9bc0779f566700b41acbebdbdd319349557ba7126643eee','0',to_date('1989/01/01','yyyy/mm/dd'));
Insert into FELHASZNALO (VEZETEKNEV,KERESZTNEV,EMAIL,JELSZO,SZEREP,SZULETESI_DATUM) values ('Feher','Borbala','Fb7@gmail.com','0d46eac393e81e06d720e95839ecf58f9adf3689c0a6a921cb76f7c237564ecf','0',to_date('1989/01/01','yyyy/mm/dd'));
Insert into FELHASZNALO (VEZETEKNEV,KERESZTNEV,EMAIL,JELSZO,SZEREP,SZULETESI_DATUM) values ('Feher','Karolina','Fk8@gmail.com','9310855d05a9500c87288d394d391c78d8c946d658d013ace35e9fa4fd830bd0','0',to_date('1989/01/01','yyyy/mm/dd'));
Insert into FELHASZNALO (VEZETEKNEV,KERESZTNEV,EMAIL,JELSZO,SZEREP,SZULETESI_DATUM) values ('Feher','Ferenc','Fk9@gmail.com','ab54fbb8b4ddb9244dda497f518782d214e127182c8d4f6bfac34f0a8497a8ee','0',to_date('1989/01/01','yyyy/mm/dd'));
Insert into FELHASZNALO (VEZETEKNEV,KERESZTNEV,EMAIL,JELSZO,SZEREP,SZULETESI_DATUM) values ('Fekete','Laszlo','Fv10@gmail.com','6ad868c9c65b9ada6152fc98b5256af1e50b5ce0c93c648a057f1d1d4e023177','0',to_date('1989/01/01','yyyy/mm/dd'));

Insert into CSOPORT (CSOPORT_NEV,TULAJ) values ('sajt10',1);
Insert into CSOPORT (CSOPORT_NEV,TULAJ) values ('palacsinta21',3);
Insert into CSOPORT (CSOPORT_NEV,TULAJ) values ('fecske30',5);
Insert into CSOPORT (CSOPORT_NEV,TULAJ) values ('Kecske210',10);
Insert into CSOPORT (CSOPORT_NEV,TULAJ) values ('macsekok217',7);
Insert into CSOPORT (CSOPORT_NEV,TULAJ) values ('torta14',4);
Insert into CSOPORT (CSOPORT_NEV,TULAJ) values ('PORT3306',8);
Insert into CSOPORT (CSOPORT_NEV,TULAJ) values ('tiramisu1024',9);

Insert into TAG (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO,CSOPORT_AZONOSITO) values (3,8,7);
Insert into TAG (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO,CSOPORT_AZONOSITO) values (4,3,4);
Insert into TAG (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO,CSOPORT_AZONOSITO) values (5,3,4);
Insert into TAG (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO,CSOPORT_AZONOSITO) values (5,10,4);
Insert into TAG (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO,CSOPORT_AZONOSITO) values (6,5,3);
Insert into TAG (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO,CSOPORT_AZONOSITO) values (6,5,5);
Insert into TAG (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO,CSOPORT_AZONOSITO) values (7,5,3);
Insert into TAG (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO,CSOPORT_AZONOSITO) values (7,5,5);
Insert into TAG (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO,CSOPORT_AZONOSITO) values (8,7,5);
Insert into TAG (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO,CSOPORT_AZONOSITO) values (9,7,5);
Insert into TAG (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO,CSOPORT_AZONOSITO) values (1,3,4);
Insert into TAG (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO,CSOPORT_AZONOSITO) values (1,5,5);
Insert into TAG (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO,CSOPORT_AZONOSITO) values (2,3,4);
Insert into TAG (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO,CSOPORT_AZONOSITO) values (2,4,6);
Insert into TAG (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO,CSOPORT_AZONOSITO) values (2,8,7);
Insert into TAG (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO,CSOPORT_AZONOSITO) values (2,10,4);

Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (3,5);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (3,6);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (3,7);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (3,8);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (4,5);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (4,6);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (4,7);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (4,8);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (5,8);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (5,9);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (5,10);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (5,11);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (6,11);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (6,12);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (1,3);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (1,4);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (1,5);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (1,6);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (1,2);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (2,7);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (2,8);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (2,9);
Insert into ISMEROS (KERELMEZO_AZONOSITO,FOGADO_AZONOSITO) values (2,10);

Insert into PRIVAT_UZENET (KULDO_AZONOSITO,SZOVEG,FOGADO_AZONOSITO) values (1,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',3);
Insert into PRIVAT_UZENET (KULDO_AZONOSITO,SZOVEG,FOGADO_AZONOSITO) values (3,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',1);
Insert into PRIVAT_UZENET (KULDO_AZONOSITO,SZOVEG,FOGADO_AZONOSITO) values (1,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',3);
Insert into PRIVAT_UZENET (KULDO_AZONOSITO,SZOVEG,FOGADO_AZONOSITO) values (3,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',1);
Insert into PRIVAT_UZENET (KULDO_AZONOSITO,SZOVEG,FOGADO_AZONOSITO) values (4,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',10);
Insert into PRIVAT_UZENET (KULDO_AZONOSITO,SZOVEG,FOGADO_AZONOSITO) values (10,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',5);
Insert into PRIVAT_UZENET (KULDO_AZONOSITO,SZOVEG,FOGADO_AZONOSITO) values (5,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',10);
Insert into PRIVAT_UZENET (KULDO_AZONOSITO,SZOVEG,FOGADO_AZONOSITO) values (10,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',5);
Insert into PRIVAT_UZENET (KULDO_AZONOSITO,SZOVEG,FOGADO_AZONOSITO) values (4,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',5);
Insert into PRIVAT_UZENET (KULDO_AZONOSITO,SZOVEG,FOGADO_AZONOSITO) values (5,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',4);
Insert into PRIVAT_UZENET (KULDO_AZONOSITO,SZOVEG,FOGADO_AZONOSITO) values (4,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',5);
Insert into PRIVAT_UZENET (KULDO_AZONOSITO,SZOVEG,FOGADO_AZONOSITO) values (5,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',4);
Insert into PRIVAT_UZENET (KULDO_AZONOSITO,SZOVEG,FOGADO_AZONOSITO) values (4,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',5);
Insert into PRIVAT_UZENET (KULDO_AZONOSITO,SZOVEG,FOGADO_AZONOSITO) values (5,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',4);
Insert into PRIVAT_UZENET (KULDO_AZONOSITO,SZOVEG,FOGADO_AZONOSITO) values (4,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',5);
Insert into PRIVAT_UZENET (KULDO_AZONOSITO,SZOVEG,FOGADO_AZONOSITO) values (5,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',4);
Insert into PRIVAT_UZENET (KULDO_AZONOSITO,SZOVEG,FOGADO_AZONOSITO) values (4,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',5);

Insert into CSOPORT_UZENET (KULDO_AZONOSITO,CSOPORT_AZONOSITO, SZOVEG) values (1,5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.');
Insert into CSOPORT_UZENET (KULDO_AZONOSITO,CSOPORT_AZONOSITO, SZOVEG) values (7,3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.');
Insert into CSOPORT_UZENET (KULDO_AZONOSITO,CSOPORT_AZONOSITO, SZOVEG) values (8,7, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.');
Insert into CSOPORT_UZENET (KULDO_AZONOSITO,CSOPORT_AZONOSITO, SZOVEG) values (9,4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.');
Insert into CSOPORT_UZENET (KULDO_AZONOSITO,CSOPORT_AZONOSITO, SZOVEG) values (3,4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.');
Insert into CSOPORT_UZENET (KULDO_AZONOSITO,CSOPORT_AZONOSITO, SZOVEG) values (1,4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.');
Insert into CSOPORT_UZENET (KULDO_AZONOSITO,CSOPORT_AZONOSITO, SZOVEG) values (10,4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.');
Insert into CSOPORT_UZENET (KULDO_AZONOSITO,CSOPORT_AZONOSITO, SZOVEG) values (4,5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.');
Insert into CSOPORT_UZENET (KULDO_AZONOSITO,CSOPORT_AZONOSITO, SZOVEG) values (10,5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.');
Insert into CSOPORT_UZENET (KULDO_AZONOSITO,CSOPORT_AZONOSITO, SZOVEG) values (4,8, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.');
Insert into CSOPORT_UZENET (KULDO_AZONOSITO,CSOPORT_AZONOSITO, SZOVEG) values (10,8, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.');

Insert into KEPES_BEJEGYZES (KEP,FELHASZNALO_AZONOSITO) values ('torta.jpg',3);
Insert into KEPES_BEJEGYZES (KEP,FELHASZNALO_AZONOSITO) values ('kutya.png',4);
Insert into KEPES_BEJEGYZES (KEP,FELHASZNALO_AZONOSITO) values ('kecske.png',5);
Insert into KEPES_BEJEGYZES (KEP,FELHASZNALO_AZONOSITO) values ('macska.png',5);
Insert into KEPES_BEJEGYZES (KEP,FELHASZNALO_AZONOSITO) values ('sajt.jpg',9);
Insert into KEPES_BEJEGYZES (KEP,FELHASZNALO_AZONOSITO) values ('aztal.jpg',11);
Insert into KEPES_BEJEGYZES (KEP,FELHASZNALO_AZONOSITO) values ('fa.jpg',11);

Insert into KEPES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO,REAKCIO) values (5,1,1);
Insert into KEPES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO,REAKCIO) values (5,2,1);
Insert into KEPES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO,REAKCIO) values (2,2,1);
Insert into KEPES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO,REAKCIO) values (4,4,1);
Insert into KEPES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO,REAKCIO) values (10,4,1);
Insert into KEPES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO,REAKCIO) values (3,5,1);
Insert into KEPES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO,REAKCIO) values (1,5,1);
Insert into KEPES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO,REAKCIO) values (5,6,0);
Insert into KEPES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO,REAKCIO) values (6,6,0);
Insert into KEPES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO,REAKCIO) values (5,7,1);
Insert into KEPES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO,REAKCIO) values (6,7,0);
Insert into KEPES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO,REAKCIO) values (3,6,1);


Insert into KEPES_BEJEGYZES_KOMMENT (SZOVEG,FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 5,1);
Insert into KEPES_BEJEGYZES_KOMMENT (SZOVEG,FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 6,1);
Insert into KEPES_BEJEGYZES_KOMMENT (SZOVEG,FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 2,2);
Insert into KEPES_BEJEGYZES_KOMMENT (SZOVEG,FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 6,2);
Insert into KEPES_BEJEGYZES_KOMMENT (SZOVEG,FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 7,3);
Insert into KEPES_BEJEGYZES_KOMMENT (SZOVEG,FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 8,3);
Insert into KEPES_BEJEGYZES_KOMMENT (SZOVEG,FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 4,4);
Insert into KEPES_BEJEGYZES_KOMMENT (SZOVEG,FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 10,4);
Insert into KEPES_BEJEGYZES_KOMMENT (SZOVEG,FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 3,6);
Insert into KEPES_BEJEGYZES_KOMMENT (SZOVEG,FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 2,6);
Insert into KEPES_BEJEGYZES_KOMMENT (SZOVEG,FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 4,7);
Insert into KEPES_BEJEGYZES_KOMMENT (SZOVEG,FELHASZNALO_AZONOSITO,KEPES_BEJEGYZES_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 11,7);

Insert into SZOVEGES_BEJEGYZES (SZOVEG,FELHASZNALO_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',2);
Insert into SZOVEGES_BEJEGYZES (SZOVEG,FELHASZNALO_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',2);
Insert into SZOVEGES_BEJEGYZES (SZOVEG,FELHASZNALO_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',1);
Insert into SZOVEGES_BEJEGYZES (SZOVEG,FELHASZNALO_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',1);
Insert into SZOVEGES_BEJEGYZES (SZOVEG,FELHASZNALO_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',3);
Insert into SZOVEGES_BEJEGYZES (SZOVEG,FELHASZNALO_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',4);
Insert into SZOVEGES_BEJEGYZES (SZOVEG,FELHASZNALO_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',5);
Insert into SZOVEGES_BEJEGYZES (SZOVEG,FELHASZNALO_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',6);
Insert into SZOVEGES_BEJEGYZES (SZOVEG,FELHASZNALO_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',7);
Insert into SZOVEGES_BEJEGYZES (SZOVEG,FELHASZNALO_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',8);
Insert into SZOVEGES_BEJEGYZES (SZOVEG,FELHASZNALO_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',9);
Insert into SZOVEGES_BEJEGYZES (SZOVEG,FELHASZNALO_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',10);
Insert into SZOVEGES_BEJEGYZES (SZOVEG,FELHASZNALO_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',11);

Insert into SZOVEGES_BEJEGYZES_KOMMENT (SZOVEG,FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',3,3);
Insert into SZOVEGES_BEJEGYZES_KOMMENT (SZOVEG,FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',3,4);
Insert into SZOVEGES_BEJEGYZES_KOMMENT (SZOVEG,FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',4,5);
Insert into SZOVEGES_BEJEGYZES_KOMMENT (SZOVEG,FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',5,7);
Insert into SZOVEGES_BEJEGYZES_KOMMENT (SZOVEG,FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',5,7);
Insert into SZOVEGES_BEJEGYZES_KOMMENT (SZOVEG,FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',5,8);
Insert into SZOVEGES_BEJEGYZES_KOMMENT (SZOVEG,FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',5,8);
Insert into SZOVEGES_BEJEGYZES_KOMMENT (SZOVEG,FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',6,10);
Insert into SZOVEGES_BEJEGYZES_KOMMENT (SZOVEG,FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO) values ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',8,5);

Insert into SZOVEGES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO,REAKCIO) values (10,1,1);
Insert into SZOVEGES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO,REAKCIO) values (9,1,0);
Insert into SZOVEGES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO,REAKCIO) values (10,2,0);
Insert into SZOVEGES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO,REAKCIO) values (9,2,1);
Insert into SZOVEGES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO,REAKCIO) values (11,2,1);
Insert into SZOVEGES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO,REAKCIO) values (6,3,1);
Insert into SZOVEGES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO,REAKCIO) values (7,3,1);
Insert into SZOVEGES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO,REAKCIO) values (8,4,1);
Insert into SZOVEGES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO,REAKCIO) values (9,5,1);
Insert into SZOVEGES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO,REAKCIO) values (5,6,1);
Insert into SZOVEGES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO,REAKCIO) values (4,8,1);
Insert into SZOVEGES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO,REAKCIO) values (11,9,1);
Insert into SZOVEGES_BEJEGYZES_REAKCIO (FELHASZNALO_AZONOSITO,SZOVEGES_BEJEGYZES_AZONOSITO,REAKCIO) values (1,11,1);
